key_xpath = {
    "C": "//li/span[@class='white-key' and @data-note='1c']",
    "D": "//li/span[@class='white-key' and @data-note='1d']",
    "E": "//li/span[@class='white-key' and @data-note='1e']",
    "F": "//li/span[@class='white-key' and @data-note='1f']",
    "G": "//li/span[@class='white-key' and @data-note='1g']",
    "A": "//li/span[@class='white-key' and @data-note='2a']",
    "B": "//li/span[@class='white-key' and @data-note='2b']",
    "2C": "//li/span[@class='white-key' and @data-note='2c']",
    "2D": "//li/span[@class='white-key' and @data-note='2d']",
    "2E": "//li/span[@class='white-key' and @data-note='2e']",
    "2F": "//li/span[@class='white-key' and @data-note='2f']",
    "2G": "//li/span[@class='white-key' and @data-note='2g']",
    "2A": "//li/span[@class='white-key' and @data-note='3a']",
    "2B": "//li/span[@class='white-key' and @data-note='3b']",
    "3C": "//li/span[@class='white-key' and @data-note='3c']",
    "3D": "//li/span[@class='white-key' and @data-note='3d']",
    "3E": "//li/span[@class='white-key' and @data-note='3e']",
    "3F": "//li/span[@class='white-key' and @data-note='3f']",
    "3G": "//li/span[@class='white-key' and @data-note='3g']",
    "3A": "//li/span[@class='white-key' and @data-note='4a']",
    "3B": "//li/span[@class='white-key' and @data-note='4b']",
}
